#!/bin/bash 

hadd -f data_total_13TeV_Output.root ~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_H_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_H_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_H_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File16.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File17.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File18.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File19.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File20.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File16.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_A_File17.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_B_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File16.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File17.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_C_File18.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File16.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File17.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File18.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File19.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File20.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File21.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File22.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File23.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File24.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_D_File25.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_E_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_E_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_E_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_E_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_E_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_E_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_E_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File16.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_F_File17.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File16.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File17.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File18.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File19.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File20.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File21.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_G_File22.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File16.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File17.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File18.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File19.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File20.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File22.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File23.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File24.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File25.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File26.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File27.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_I_File28.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_K_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_K_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_K_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_K_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_K_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_K_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_K_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_K_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_K_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_K_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File16.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File17.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File18.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File19.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File20.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File21.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File22.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File23.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File24.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File25.root \
~/Year-4-Project/Y4Example/Output_Datarun_16_period_L_File26.root \