#!/bin/bash 

hadd -f data15_13TeV_Output.root ~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_D_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_E_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_F_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_G_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_H_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_H_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_H_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File1.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File2.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File3.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File4.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File5.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File6.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File7.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File8.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File9.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File10.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File11.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File12.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File13.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File14.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File15.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File16.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File17.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File18.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File19.root \
~/Year-4-Project/Y4Example/Output_Datarun_15_period_J_File20.root \

